### ISSUE TITLE
Hi Zkrige, Would you please look into the issue as JSInterface method is not called with the updated swift version. Please note, it's working fine with swift version 3.0.

### ISSUE THREAD

**Issue by SantoshINT** [zkrige/EasyJSWKWebView#5]

**Comment by SantoshINT** [comment]
Would you please look into the issue as JSInterface method is not called with the updated swift version. Please note, it's working fine with swift version 3.0. When tested with Safari, getting the error:
TypeError: undefined is not a function (near '...JSInterface.testWithFuncParam...')
TypeError: JSInterface.test is not a function. (In 'JSInterface.test()', 'JSInterface.test' is undefined)

**Comment by zkrige** [comment]
I'll take a look at it this morning and see what i can find

**Comment by zkrige** [comment]
@SantoshINT can you send me an example project in swift?

**Comment by SantoshINT** [comment]
Hi zkrige,
Thank you for your kind response. Now, the issue is resolved with a minor change in the JSInterface class. Actually, this library is in the Objective C language so '@objc' keyword is required in the method declaration of the JSInterface class because method call is based on ObjC.

**Comment by zkrige** [comment]
ah yes - I was going to suggest something like that. unfortunately we're using some objc code that is not able to convert to swift, so we have to keep the framework as objc. I'll add some notes to the readme for swift implementations
